import argparse
from pathlib import Path
import textwrap

from scripts.execute_and_convert_nbs import execute_and_convert_nbs_to_json
from scripts.generate_page_html import generate_page_html
from scripts.process_hnn_commit_hashes import get_hnn_commit_hash, validate_hnn_versions

textbook_root_path = Path(__file__).parents[0]


def main():
    """See 'python build.py --help' for explanation of the code."""

    # Define command line arguments
    # ----------------------------------------------------------------------------------
    parser = argparse.ArgumentParser(
        description=textwrap.dedent("""
Synopsis:
---------
    Build the HNN Textbook website by processing markdown and Jupyter notebooks into
    HTML.

    This code orchestrates the complete website construction process for the HNN (Human
    Neocortical Neurosolver) Textbook. It validates the installed hnn-core version,
    executes Jupyter notebooks (if requested), and converts markdown content into
    structured HTML pages with navigation.

    Required Files and Directory Structure
    --------------------------------------
    All paths are relative to the "textbook-root" directory. This is assumed to be the
    directory named 'textbook' that contains the file 'build.py', though you can specify
    your own textbook-root location using '--custom-root-path'. Any textbook-root
    directory should contain the following files and folders in the below structure.

    Content Directory: '<textbook-root>/content/'
    ======================================
    This is the main directory for storing website content.

    In the top level of the directory (i.e. '<textbook-root>/content/'), you can add
    markdown page files (which author the webpages), Jupyter Python notebooks, and local
    images in an 'images/' subdirectory.

    You can also create subdirectories to define "sections" or chapters of your website
    (e.g. '<textbook-root>/content/05_erps/'). The "sections" have their title (as
    displayed on the website) defined in a special 'README.md' file inside the section
    subdirectory. Section subdirectories can also contain markdown page files, Jupyter
    Python notebooks, and local images in an 'images/' subdirectory.

    Markdown page files should follow this naming scheme: '<2-digit number>_<name>.md',
    for example '<textbook-root>/content/05_erps/02_hnn_core.md'. Each markdown page
    file will eventually be built into an output HTML file where the numerical prefix is
    removed, and the filetype is HTML; continuing our example,
        'textbook/content/05_erps/02_hnn_core.md'
    will become
        'textbook/content/05_erps/hnn_core.html'
    The numerical prefix in the filename is what is used to decide the ordering of the
    different webpages, both within any sections and across the website overall.

    Jupyter Python notebooks should end in '.ipynb' but otherwise can be named anything.
    Importantly, notebook content is NOT automatically displayed on the website!
    Instead, to insert the contents of a notebook (including existing cells and possible
    future output cells), you must insert the name of the notebook somewhere in a
    markdown page file. For example, the markdown page file
    'textbook/content/05_erps/02_hnn_core.md' includes the following content:
        [[plot_simulate_evoked.ipynb]]
    which determines on which page and where on that page to insert the notebook's
    contents.

    Finally, '<textbook-root>/content/' should also contain an 'assets/' subdirectory
    which contains your CSS (filename 'styles.css') and static icon assets.

    All other files inside '<textbook-root>/content/' will output files which are
    generated by the build system, either as a result of notebook execution or website
    building. This includes '*.html' files, '*.json' files, and 'output_nb_<notebook
    name>/' subdirectories. HTML files can be safely deleted and then regenerated on
    website building. JSON and 'output_nb_*' files *can* technically be deleted and
    regenerated if you must, but are generally kept and tracked on git, and *should*
    generally not be deleted. In particular, JSON files store the most recent execution
    history of each notebook (which we track to decide whether a notebook has been
    updated), and 'output_nb_*' tends to store heavy image assets which tend *not* to
    change between hnn-core code versions. In other words, you should feel free to
    delete HTML files (which can do using `make clean`) but should refrain from deleting
    JSON and 'output_nb_*' files.

    For example, a valid and minimal file structure of the content directory might look
    like this, before website building:

    ```
    textbook/
             content/
                     00_preface.md
                     01_erps/
                             README.md
                             01_erps_in_gui.md
                             02_erps_in_api.md
                             simulate_erps_api.ipynb
                             images/
                                    erp_fig_01.png
                                    erp_fig_02.gif
                     assets/
                            icons/
                                  bluesky.png
                            styles.css
    ```

    Output Directories:
    ===================
    If '--code-version' is set to 'stable' (the default), then each output file (HTML,
    notebook JSON output if executed, and 'output_nb_*' if executed) will go in the same
    directory as the file used to create them under the '<textbook-root>/content/'
    directory, unless you also pass '--build-directory=dev' which will force all output
    files to be built in the 'dev' directory.

    Else, if '--code-version' is set to anything else ('master', 'custom', or
    'no-check'), then each output file will go into a new directory with the same name
    and structure as the file used to create them, *except* that each will be inside
        '<textbook-root>/dev/'
    instead of
        '<textbook-root>/content/'
    This "dev" folder will be created if it does not exist, is intended for examination
    of output and comparison with '<textbook-root>/content/', and can be safely deleted. 

    You can also override the automatic output directory selection by explicitly
    choosing to build into either the 'content' directory (by passing
    '--build-directory=content') or the 'dev' directory (by passing
    '--build-directory=dev') regardless of the '--code-version' argument.

    Scripts Directory: 'textbook/scripts/'
    ======================================
    This is the directory for storing both Python code called by 'build.py' and metadata
    about Jupyter notebook execution statues (which is updated automatically). Aside
    from changing the code or inspecting the JSON files during debugging, the only file
    you are likely to interact with is 'textbook/scripts/nbs_to_skip.json' in case you
    want to indicate that a new or existing notebook should be skipped from execution.

    Data:
        - nb_hashes.json : SHA-256 hashes of notebook content to detect changes
        - nbs_to_skip.json : List of notebooks to skip during execution
        - hier_index.json : Hierarchical page index (generated if --save-indices=True)
        - flat_index.json : Flat page index for navigation (generated if
            --save-indices=True)

    Templates Directory: 'textbook/templates/'
    ==========================================
    This directory contains both generic HTML templates and the Javascript used in the
    website. Some of the HTML templates are loaded and then modified during the build
    process.

    - dev_scripts.js : Development-specific JavaScript
    - footer.html : Page footer with prev/next navigation placeholders
    - header.html : HTML <head> section with CSS/JS imports
    - md_yaml_metadata.txt : YAML metadata template prepended to markdown page content
    - script.html : JavaScript includes at end of page
    - scripts.js : Main JavaScript functionality for interactive features
    - topbar.html : Top navigation bar

    Bibliography File:
    ==================
    - textbook/textbook-bibliography.bib : BibTeX bibliography for citations in markdown

    Website Construction Process
    ----------------------------
    1. **Parse command-line arguments** to determine:
        - Which hnn-core version to use and possibly validate against (see
            '--code-version' argument help)
        - Which notebooks to execute, if any (see '--execution-type' argument help)
        - Output directory type based on '--code-version', unless you pass a specific
            directory type to the '--build-directory' argument

    2. **Validate hnn-core installation** (via `get_hnn_commit_hash`):
        - Retrieve installed hnn-core version/commit from `pip freeze`
        - Fetch requested version/commit from PyPI or GitHub API (unless
            '--code-version=no-check')
        - Verify installed version matches requested version (unless
            '--code-version=no-check')
        - Determine commit hash for notebook execution history tracking

    3. **Execute Jupyter notebooks** (via `execute_and_convert_nbs_to_json`):
        - Scan '<textbook-root>/content' directory for .ipynb files
        - Check notebook hashes to detect changes (from
            'textbook/scripts/nb_hashes.json') and update if changes are detected
        - Execute notebooks based on '--execution-type' argument and skip list (i.e.
            'textbook/scripts/nbs_to_skip.json')
        - Extract HTML from executed notebook cells (code, output, and markdown cells)
        - Save structured notebook outputs as '.json' files alongside '.ipynb' files
        - Optionally generate standalone HTML files for each notebook (if
            '--save-standalone-nb-html' is true)
    4. **Generate HTML pages** (via `generate_page_html`):
        - Scan '<textbook-root>/content' directory for numbered markdown files (##_*.md)
        - Customize appopriate HTML templates based on each markdown page
        - For each markdown file:
            a. Create hierarchical- and flat-indices of pages for navigation (footer and
                 sidebar)
            b. Convert markdown page content to HTML using Pandoc with citation support
            c. Embed notebook outputs using [[<notebook_name>.ipynb]] syntax
            d. Inject HTML templates (header, navbar, topbar, footer, scripts)
            e. Adjust relative image asset paths based on page depth
            f. Save final HTML page

    Notes
    -----
    - You can mix and match all values of '--code-version' and '--execution-type'
        arguments.
    - The build process requires internet access unless using '--code-version=no-check'.
    - Page navigation order is determined by numerical prefixes (##_) in filenames, in
        addition to numerical prefixes (##_) in their section subdirectory names if they
        are inside subdirectories.

    Examples (not comprehensive)
    ----------------------------
    1. Do not execute any notebooks, and build the website using the latest stable
        release in your local `content` directory:

        $ python build.py

    2. Re-execute any notebooks that have been updated/changed (excluding those set to
        be skipped) using the latest stable release (default), and build the website in
        your local `content` directory:

        $ python build.py --execution-type=updated-unskipped-notebooks

    3. Re-execute any notebooks that have been updated/changed (excluding those set to
        be skipped) using the latest master (development) branch, and build the website
        in your local `dev` directory (creating it if necessary):

        $ python build.py --execution-type=updated-unskipped-notebooks
        --code-version=master

    4. Re-execute any notebooks that have been updated/changed (excluding those set to
        be skipped) using the current master (development) branch that you have
        installed, and build the website in your local `dev` directory (creating it if
        necessary):

        $ python build.py --execution-type=updated-unskipped-notebooks
        --code-version=master

    5. Re-execute any notebooks that have been updated/changed (excluding those set to
        be skipped) using a custom fork/commit, and build the website in your local
        `dev` directory (creating it if necessary):

        $ python build.py --execution-type=updated-unskipped-notebooks
        --code-version=custom --custom-owner-commit=username:abc123

    6. Re-execute all notebooks, excluding those set to be skipped, using the latest
        stable release (default), and build the website in your local `content`
        directory:

        $ python build.py --execution-type=all-unskipped-notebooks

    7. Re-execute all notebooks, excluding those set to be skipped, using whatever
       HNN-Core version is installed locally, and build the website in your local `dev`
       directory:

        $ python build.py --execution-type=all-unskipped-notebooks
        --code-version=no-check

    8. Re-execute all notebooks, excluding those set to be skipped, using whatever
       HNN-Core version is installed locally, and build the website in your local
       `content` directory:

        $ python build.py --execution-type=all-unskipped-notebooks
        --code-version=no-check --build-directory=content

    9. Re-execute ALL notebooks, INCLUDING those set to be skipped, using the latest
        stable release (default), and build the website in your local `content`
        directory:

        $ python build.py --execution-type=absolutely-all-notebooks

    10. Do not execute any notebooks, and build the website using whatever version of
        HNN-Core is installed locally, and build the website in your local `content`
        directory:

        $ python build.py --code-version=no-check --build-directory=content
"""),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--build-directory",
        action="store",
        default="auto",
        choices=[
            "auto",
            "content",
            "dev",
        ],
        help=textwrap.dedent("""
Specify whether to build the website output files in the 'content' or 'dev' directory
(creating the 'dev' folder if necessary). The three options are:

- 'auto': (default) Select output directory based on the '--code-version' argument. Code
    versions of '--code-version=stable' (the default) build in 'content', while all
    other code versions build in 'dev', creating it if necessary.
- 'content': Force all output files to be built in the 'content' directory.
- 'dev': Force all output files to be built in the 'dev' directory, creating it if
  necessary.
"""),
    )
    parser.add_argument(
        "--code-version",
        action="store",
        default="stable",
        choices=[
            "stable",
            "master",
            "custom",
            "no-check",
        ],
        help=textwrap.dedent("""
Specify which version of HNN-core you want to use for building the textbook. The default is
'stable'. This validates whether you have the correct version installed in your local environment
environment unless you choose 'no-check' which simply uses the installed version without checking
anything. The four options are:

- 'stable': This builds the textbook using the latest stable version of HNN-Core. This
    version is validated based on a request to PyPI, checking if your version is using the latest
    stable. This produces a 'stable' build, meaning it creates the output HTML files in the
    '<textbook-root>/content' folder (unless you also pass '--build-directory=dev').
- 'master': This builds the textbook using the latest development version of
    HNN-Core. This version is validated based on a request to Github, checking if your version is
    using the latest commit on the 'master' branch. This produces a 'dev' build, meaning it creates
    the output HTML files in the '<textbook-root>/dev' folder (unless you also pass
    '--build-directory=content').
- 'custom': This builds the textbook using a custom commit and, optionally, a custom
    repository-owner's version of HNN-Core. If using this option, you must provide the
    repository-owner and/or commit you want using the '--custom-repo-commit' argument. This version
    is validated based on a request to Github, checking for the existence of the commit you have
    provided. This produces a 'dev' build, meaning it creates the output HTML files in the
    '<textbook-root>/dev' folder (unless you also pass '--build-directory=content').
- 'no-check': This builds the textbook using whatever is the current installed commit of
    HNN-Core. This does not check anything about the version you have currently installed. This
    produces a 'dev' build, meaning it creates the output HTML files in the '<textbook-root>/dev'
    folder (unless you also pass '--build-directory=content').
"""),
    )
    parser.add_argument(
        "--execution-type",
        action="store",
        default="no-execution",
        choices=[
            "no-execution",
            "updated-unskipped-notebooks",
            "all-unskipped-notebooks",
            "absolutely-all-notebooks",
        ],
        help=textwrap.dedent("""
Specify different criteria for which notebooks you want to execute before converting
them to HTML. The default is 'no-execution'. The four options are below, in order of
more execution:

- 'no-execution': This will not execute any notebooks. You may receive warnings if
    specific notebooks should be executed.
- 'updated-unskipped-notebooks': Execute only notebooks which have been
    updated/changed or are new, excluding notebooks flagged for skipping.
- 'all-unskipped-notebooks': Execute all notebooks except those flagged for
    skipping.
- 'absolutely-all-notebooks': Execute all notebooks.
"""),
    )
    parser.add_argument(
        "--custom-owner-commit",
        type=str,
        help=textwrap.dedent("""
Optionally provide a specific commit of HNN-core to use in the form of
<owner>:<commit>. For example, if you wanted to build using the commit at
https://github.com/asoplata/hnn-core/commit/92b000c597052a661d9e177b8754695446336b96 ,
you would use '--custom-owner-commit asoplata:92b000c'. This assumes that the
fork/repository name is always 'hnn-core'. This is required if you are using
'--code-version custom'.
"""),
    )
    # AES Not sure we want to support this, but leaving it as an option since I assume
    # this case was the reason why `os.getcwd()` is used so much in the scripts instead
    # of absolute paths.
    parser.add_argument(
        "--custom-root-path",
        type=str,
        help=textwrap.dedent("""
Optionally provide a different 'root' location for your textbook files,
"""),
    )
    parser.add_argument(
        "--save-indices",
        action="store_true",  # Confusingly, this defaults to False
        help=textwrap.dedent("""
Optionally provide whether or not to save the webpage-indexing files during the build
process. Defaults to False.
"""),
    )
    parser.add_argument(
        "--save-standalone-nb-html",
        action="store_true",  # Confusingly, this defaults to False
        help=textwrap.dedent("""
Optionally provide whether or not to save each Jupyter Python notebook's raw HTML output
during the build process. Defaults to False.
"""),
    )

    # Process CLI arguments, and set paths
    # ----------------------------------------------------------------------------------
    args = parser.parse_args()

    if args.custom_root_path:
        root_path = args.custom_root_path
    else:
        root_path = textbook_root_path

    content_path = Path(root_path / "content")
    hier_index_path = Path(root_path / "scripts" / "hier_index.json")
    flat_index_path = Path(root_path / "scripts" / "flat_index.json")
    nb_hashes_path = Path(root_path / "scripts" / "nb_hashes.json")
    nb_skips_path = Path(root_path / "scripts" / "nbs_to_skip.json")
    # The "templates" directory is assumed to contain at least the following files:
    # - footer.html
    # - header.html
    # - md_yaml_metadata.txt
    # - script.html
    # - scripts.js
    # - topbar.html
    templates_path = Path(root_path / "templates")

    # This "printed" variable is only used here for logging, never for actual output
    # pathing.
    printed_output_dir = (
        content_path if args.code_version == "stable" else Path(root_path / "dev")
    )
    print(
        "Configuration: Choice of notebooks to execute will be based on "
        f"\n    '--execution-type={args.execution_type}'"
        "\nConfiguration: Choice of HNN version to use will be based on "
        f"\n    '--code-version={args.code_version}'"
        "\nConfiguration: Local website files will be built in "
        f"\n    '{printed_output_dir}'"
    )

    # Begin the actual work: First, figure out the environment and version:
    # ----------------------------------------------------------------------------------
    installed_commit = get_hnn_commit_hash()

    # We can't pre-empt this function in the no-validation case, since the value of the
    # hash varies between "stable" and "dev" builds
    hnn_commit_hash = validate_hnn_versions(
        installed_commit,
        args.code_version,
        custom_owner_commit=args.custom_owner_commit,
    )

    # Determine if we're in a "dev" build or not
    if args.build_directory == "auto":
        is_dev_build = False
        if args.code_version in ("master", "custom", "no-check"):
            is_dev_build = True
    elif args.build_directory == "content":
        # Override default behavior and force a "content" build
        is_dev_build = False
    elif args.build_directory == "dev":
        # Override default behavior and force a "dev" build
        is_dev_build = True

    # Execute appropriate Jupyter notebooks, and save their output for later webpage
    # assembly:
    # ----------------------------------------------------------------------------------
    execute_and_convert_nbs_to_json(
        content_path,
        nb_hashes_path,
        nb_skips_path,
        args.execution_type,
        is_dev_build,
        hnn_commit_hash,
        args.save_standalone_nb_html,
    )

    # Finally, use the Markdown files and Jupyter notebook output to assemble the
    # webpages and website as a whole:
    # ----------------------------------------------------------------------------------
    generate_page_html(
        content_path,
        templates_path,
        is_dev_build,
        save_indices=args.save_indices,
        hier_index_path=hier_index_path,
        flat_index_path=flat_index_path,
    )


if __name__ == "__main__":
    main()
